name: build-scratch-blocks
on:
    push: # Runs whenever a commit is pushed to the repository
    workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
jobs:
    setup:
      runs-on: ubuntu-latest
      env:
        PROJECT_PATH: ./scratch-blocks
      steps:
        - run: |
            for F in chrome chromium chromedriver; do
              which $F && $F --version || echo Not found: $F
            done
        - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        - name: Check Python version
          run: python --version
        - name: Setup Node
          uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
          with:
            node-version-file: '.nvmrc'
        # TODO: tests
        - name: Install Node Dependencies
          # The --legacy-peer-deps flag is a TEMPORARY fix during the Blockly 12 beta.
          # It should be removed once the @blockly/* packages support Blockly 12.
          run: npm ci --legacy-peer-deps
        - name: Build
          run: npm run build
        # - name: Deploy playground to GitHub Pages
        #   uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        #   with:
        #     github_token: ${{ secrets.GITHUB_TOKEN }}
        #     publish_dir: ./gh-pages
        #     full_commit_message: "Build for ${{ github.sha }} ${{ github.event.head_commit.message }}"
        #     enable_jekyll: true
        - name: Run semantic-release
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: npx --no -- semantic-release
